### ISSUE TITLE
Update supported node version to ^10.8.0

### ISSUE THREAD

**Issue by OFranke** [quantumblacklabs/kedro-ui#48]
## Description
I am trying to use kedro-viz in a fresh create-react-app project. I am facing a compatibility problem as kedro-ui supports only node 10.8.0. I've checked out kedro-ui master and ran all the tests with node 10.17.0 -> successfully.

## Context
I can not use the kedro-viz React component.

## Expected Result
Update supported node version.

## Actual Result
Error in npm install occurs

```
error @quantumblack/kedro-ui@1.1.1: The engine "node" is incompatible with this module. Expected version "10.8.0".
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro UI version used (`npm run version:get`): 1.1.1
* Node version used (`node -v`): 10.17.0
* Operating system and version: MacOS

## Checklist
Include labels so that we can categorise your issue:

- [medium] Add a "Priority" label to the issue

**Comment by richardwestenra** [comment]
Thanks @OFranke! Sorry we didn't notice this until now. Would simply adding `^` in front of the node/npm version numbers suffice? e.g.
```
  "engines": {
-    "node": "10.8.0",
-    "npm": "6.3.0"
+    "node": "^10.8.0",
+    "npm": "^6.3.0"
  },
```
